// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2DYlQBDZSc_wI0am-9zfqsVVP8ccI5us',
    appId: '1:1061779072793:web:9a56e5b6f5440c17eb0788',
    messagingSenderId: '1061779072793',
    projectId: 'thyzone-10134',
    authDomain: 'thyzone-10134.firebaseapp.com',
    databaseURL: 'https://thyzone-10134-default-rtdb.firebaseio.com',
    storageBucket: 'thyzone-10134.firebasestorage.app',
    measurementId: 'G-2WSQHC6VNK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCtjtjjVpXbjlKYnGx1fYU4ZvXAYSkcYM',
    appId: '1:1061779072793:android:e9feec7209faafd0eb0788',
    messagingSenderId: '1061779072793',
    projectId: 'thyzone-10134',
    databaseURL: 'https://thyzone-10134-default-rtdb.firebaseio.com',
    storageBucket: 'thyzone-10134.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9B9mHCxTl1Y6Dom82-FKc26WSxqe2vCo',
    appId: '1:1061779072793:ios:802f19b8b1ae2604eb0788',
    messagingSenderId: '1061779072793',
    projectId: 'thyzone-10134',
    databaseURL: 'https://thyzone-10134-default-rtdb.firebaseio.com',
    storageBucket: 'thyzone-10134.firebasestorage.app',
    iosBundleId: 'com.example.bai2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9B9mHCxTl1Y6Dom82-FKc26WSxqe2vCo',
    appId: '1:1061779072793:ios:802f19b8b1ae2604eb0788',
    messagingSenderId: '1061779072793',
    projectId: 'thyzone-10134',
    databaseURL: 'https://thyzone-10134-default-rtdb.firebaseio.com',
    storageBucket: 'thyzone-10134.firebasestorage.app',
    iosBundleId: 'com.example.bai2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2DYlQBDZSc_wI0am-9zfqsVVP8ccI5us',
    appId: '1:1061779072793:web:2d11752bade83e49eb0788',
    messagingSenderId: '1061779072793',
    projectId: 'thyzone-10134',
    authDomain: 'thyzone-10134.firebaseapp.com',
    databaseURL: 'https://thyzone-10134-default-rtdb.firebaseio.com',
    storageBucket: 'thyzone-10134.firebasestorage.app',
    measurementId: 'G-N9EN2RMXV9',
  );
}
